### ISSUE TITLE
How to forward video based on time?

### ISSUE THREAD

**Issue by ananth10** [halilozercan/BetterVideoPlayer#10]
I need to forward the video programmatically based on time, e.g need to play 10:15 frame in the video when player start. can you please tell me how to do it?

**Comment by halilozercan** [comment]
I'm not quite sure if I understood your problem correctly. Can you explain it a bit more?

**Comment by ananth10** [comment]
@halilozercan  Consider like a 15 mins video . When open activity player will play video automatically because i have set **autoPlay**.  in my layout  i have set static time like 3 min , 6 min ,9 min etc.. so when i click that time. i need to move video to that time(like forwating). so how to do it?

**Comment by halilozercan** [comment]
```
// Seeks to a position in the video. player.seekTo(int);
```

Given integer should be in seconds. To warn you though, video encoders usually divide the video in chunks that are around 3-7 seconds and Android stock MediaPlayer API seeks to head of these chunks. 

This means that sometimes when you call ```seekTo(100)``` it may seek to a position under 100 seconds like 98 or 99.

**Comment by ananth10** [comment]
@halilozercan  Thanks, Should i pass seconds or milliseconds?

**Comment by halilozercan** [comment]
> Given integer should be in seconds

**Comment by ananth10** [comment]
@halilozercan Thanks

**Comment by ananth10** [comment]
@halilozercan  Its a 36 sec video . when i set player.seekTo(20)sec. its not working. but if i convert sec to millisec. then its working . getting below log when pass 20 sec to seekTo.

`V/MediaPlayer-JNI: seekTo: 20(msec)`

Let me know that Should i pass sec or millisec ?
