### ISSUE TITLE
NullPointerException - After completion of video playing clicking on replay control 

### ISSUE THREAD

**Issue by srikanth104** [halilozercan/BetterVideoPlayer#17]
Android: 6.0.1
Android Build: MMB29M.N910GDTU1DQD4
Manufacturer: samsung
Model: SM-N910G
Thread: main-1
CrashReporter Key: 39646626-6511-1F75-8090-1570DF6712CA423299B3
Start Date: Mon May 15 12:18:01 GMT+05:30 2017
Date: Mon May 15 12:20:15 GMT+05:30 2017

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.media.MediaPlayer.isPlaying()' on a null object reference
	at com.halilibo.bettervideoplayer.BetterVideoPlayer.onClick(BetterVideoPlayer.java:804)
	at android.view.View.performClick(View.java:5697)
	at android.view.View$PerformClick.run(View.java:22526)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by halilozercan** [comment]
Unfortunately I could not reproduce the same error. Can you provide more details?

**Comment by srikanth104** [comment]
@halilozercan sorry it was my mistake, Issue resolved.

**Comment by santhoshrao519** [comment]
I'm using bvp in a listview, when i scroll the list, the video turns into black and when i click a particular video it is showing following error

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.media.MediaPlayer.isPlaying()' on a null object reference

**Comment by halilozercan** [comment]
Playing video in a listview or scrollview is a challenging subject. Although BetterVideoPlayer doesn't have an integrated support for such use cases, it is still possible. I suggest to you look for listview video manager. I'm currently on mobile so can't link it here.

**Comment by santhoshrao519** [comment]
Firstly thanks for the reply, i have googled it out about listview video manager.
As i have found following link
https://github.com/danylovolokh/VideoPlayerManager

Please do confirm this

**Comment by halilozercan** [comment]
Yes, you found the correct repository. It is a great tool to manage multiple video players. You may have troubles integrating BetterVideoPlayer to manager and it may require you to edit the source code.

**Comment by santhoshrao519** [comment]
what i need to change the code in example, can you please brief once
