### ISSUE TITLE
Brightness adjustment on scroll-up not working

### ISSUE THREAD

**Issue by athirukk** [halilozercan/BetterVideoPlayer#18]
Do I need to enable any property for the brightness adjustment to work? Volume adjustment works fine in the player.

BTW, its neat to use when compared to other players. Good work so far 👍

**Comment by halilozercan** [comment]
Did you use ```setWindow``` ? That is necessary for brightness to work

**Comment by athirukk** [comment]
Yup, that worked.
player.setWindow(getActivity().getWindow());
