### ISSUE TITLE
How use default android LoadingStyle

### ISSUE THREAD

**Issue by developerGM** [halilozercan/BetterVideoPlayer#26]
I want use the android loading style. How can I do ?

**Comment by halilozercan** [comment]
The library uses [SpinKit](https://github.com/ybq/Android-SpinKit) for loading animations and I think it does not involve default loading style. However, you can fork the repository and add support for this.

**Comment by developerGM** [comment]
Ok, thanks for your reply. And I can't change loading size too ? right ?

**Comment by halilozercan** [comment]
That's right unfortunately.
