### ISSUE TITLE
.m3u8 files support

### ISSUE THREAD

**Issue by tonywamba** [halilozercan/BetterVideoPlayer#31]
Would be awesome to be able to play .m3u8 video playlist files

**Comment by marnylopez** [comment]
I have managed to play .m3u8 files with this library..

**Comment by halilozercan** [comment]
> I have managed to play .m3u8 files with this library..

Would'nt it be cool to share your solution? :) 

I've been busy for a while with my studies and work, sorry for not responding to issues frequently.

**Comment by marnylopez** [comment]
Sure..

Its as easy as:

`            
// Sets the source to the HTTP URL held in the TEST_URL variable 2 play files, use Uri.fromFile(new File("..."))
player.setSource(Uri.parse(this.ChannelUrl));
`

the ChannelUrl variable is just a link with a .m3u8 file extension.

**Comment by halilozercan** [comment]
Well then Android MediaPlayer natively supports m3u8. I didn't know that. Thanks :+1:
