### ISSUE TITLE
seekTo(0) does not go to the position 0

### ISSUE THREAD

**Issue by carlastabile** [halilozercan/BetterVideoPlayer#32]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ x] I have verified that I am using the latest version of Better Video Player.
- [ x] I have given my issue a non-generic title.
- [ x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
- Better Video Player version: `1.1.0`
- Device OS version: `6.0.1`
- Device Manufacturer: `BQ`
- Device Name: `Aquarius U Plus`

-Also, please wrap Java with correct syntax highlighting.
 **I'm using Kotlin** 

    fun initBtn() {
        var startedYet = false

        initPlayer()

        fitnessTestStartEndBtn.onClick {
            if (!startedYet) {
                if (fitnessTestPlayer.isPrepared) {
                    if (fitnessTestPlayer.currentPosition != 0) fitnessTestPlayer.seekTo(0)
                    startedYet = true
                    fitnessTestPlayer.start()
                }
            } else {
                fitnessTestPlayer.pause()
                startedYet = false
            }
        }
    }

    fun initPlayer() {
        fitnessTestPlayer.reset()
        fitnessTestPlayer.setCallback(this)

        if (whichExercise == RESQUEST1)
            fitnessTestPlayer.setSource(Uri.parse(myUrl1))
        else if (whichExercise == RESQUEST2) {
            fitnessTestPlayer.setSource(myUrl2))
        }

        fitnessTestPlayer.setAutoPlay(false)
        fitnessTestPlayer.setLoop(true)
    }

    override fun onPause() {
        fitnessTestPlayer.pause()
        super.onPause()
    }

###### Reproduction Steps

-1. Set a data source to player
-2. Play it, finish or pause activity and reopen it 

###### Expected Result
- Set a data source to player
- Play it, finish or pause activity and reopen it 
- Player should start the video from the beggining

###### Actual Result
- Player remains in the position where it was paused before fenishing or pausing the activity

**Comment by halilozercan** [comment]
I haven't used Kotlin, but I think you should'nt rely on your ```startedYet``` variable. BetterVideoPlayer has a callback interface and many getter methods to understand its lifecycle. 

I will try to reproduce this issue when I have time. As I understand, your problem is that when you pause and return back to the activity, it does not seek to starting position.

**Comment by carlastabile** [comment]
@halilozercan yes thats my problem. You are right, I think ill stop using the startedYet variable, but I don't think its related to the main  problem.

Thanks for your quick answer
