### ISSUE TITLE
Video skipping seconds when pause / play

### ISSUE THREAD

**Issue by JoaoArmandoo** [halilozercan/BetterVideoPlayer#42]
Hello, I am facing serious problems, when I pause a video and play next, the video that for example was in 2 seconds, it changes to 7, the image is frozen until the audio arrives in the 7 seconds. Apparently the audio does not have this problem, it continues where it stopped, but the video, skips several pictures.

I posted a video on youtube to better show the problem, observe the timing of the video, when paused, and when played.

My XML:    
```
<com.halilibo.bettervideoplayer.BetterVideoPlayer
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/player"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
```

My Code:
public class videoPlayerActivity extends AppCompatActivity implements BetterVideoCallback {
    private BetterVideoPlayer player;

    int position = 0;

    String TAG = "statusVideo";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_player);

        player = (BetterVideoPlayer) findViewById(R.id.player);
        player.setCallback(this);
        player.setSource(Uri.parse("https://instagram.fbhz2-1.fna.fbcdn.net/t50.2886-16/22251533_131289287518083_2969207214956347392_n.mp4"));

    }
    @Override
    public void onPause() {
        super.onPause();
        // Make sure the player stops playing if the user presses the home button.
        player.pause();
    }

    // Methods for the implemented EasyVideoCallback

    @Override
    public void onStarted(BetterVideoPlayer player) {
        Log.i(TAG, "Started");

    }

    @Override
    public void onPaused(BetterVideoPlayer player) {
        Log.i(TAG, "Paused");

    }

    @Override
    public void onPreparing(BetterVideoPlayer player) {
        Log.i(TAG, "Preparing");
    }

    @Override
    public void onPrepared(BetterVideoPlayer player) {
        Log.i(TAG, "Prepared");
    }

    @Override
    public void onBuffering(int percent) {
        Log.i(TAG, "Buffering " + percent);
    }

    @Override
    public void onError(BetterVideoPlayer player, Exception e) {
        Log.i(TAG, "Error " +e.getMessage());
    }

    @Override
    public void onCompletion(BetterVideoPlayer player) {
        Log.i(TAG, "Completed");
    }

    @Override
    public void onToggleControls(BetterVideoPlayer player, boolean isShowing) {
        Log.i(TAG, "Controls toggled " + isShowing);
    }

}``

**Comment by halilozercan** [comment]
Hey, first of all thanks for detailed explanation of your problem. Secondly, your youtube video is removed for copyright infringement. You can upload any mp4 file here http://halilibo.com/filez/

About your problem, I'm not sure if I understood it correctly. I tried to reproduce your issue with the same link in demo app. Unfortunately the problem you mentioned didn't occur in emulator. Sadly, I cannot experiment on a physical device right now.

**Comment by JoaoArmandoo** [comment]
Hello, thank you for your precious dedication to answering my question.
I checked this also in the emulator, but this problem did not happen in the emulator. I tried several different urls, but in the physical device this continued, it is worth remembering that the same problem happened with other libs of video player.
I'm testing on a Asus zenfone 2 ZE551 handset, I'll now try on an Asus zenfone Go Live, to check if the problem is only on my device, I'll soon update it, here's the video up again:
[http://halilibo.com/filez/i/5HWRp6q.mp4](url)

**Comment by JoaoArmandoo** [comment]
On zenfone 2, i'm using android 5.0 API 21.

**Comment by JoaoArmandoo** [comment]
I just tested on Asus zenfone Go Live, api 22, and the problem did not reproduce. I'll be trying with versions below api 22 to check if this might be the problem.

**Comment by JoaoArmandoo** [comment]
I just tested in an emulator with api 16, the problem also did not reproduce.
