### ISSUE TITLE
Please add screen rotation feature

### ISSUE THREAD

**Issue by kksingla** [halilozercan/BetterVideoPlayer#45]
I have implemented the screen rotation using screenOrientation, but when video changed then video is not fit accordingly

**Comment by kksingla** [comment]
@halilozercan Please help

**Comment by vinayAryabhat** [comment]
bro.... try these
      in AndroidManifest.xml  
       <activity
            android:name=".activity.VideoPlayer"
            android:screenOrientation="sensor"
            android:configChanges="orientation|keyboardHidden|screenLayout|screenSize"
            android:theme="@style/AppTheme.VideoPlayer"
            android:label="video player">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
       </activity>

      in VideoPlayer.java  (in onCreate)
        player.setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN);
