### ISSUE TITLE
is it possible to move from player to full screen without an external button?

### ISSUE THREAD

**Issue by razmaimon** [halilozercan/BetterVideoPlayer#48]
-- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
-- [x ] I have verified that I am using the latest version of Better Video Player.
-- [ x] I have given my issue a non-generic title.
-- [ x] I have read over the documentation (before asking questions on how to do something).
-
-###### Include the following:
- - Better Video Player version: `1.1.0`
- - Device OS version: `7.0`
- - Device Manufacturer: `Samsung`
- - Device Name: `S8+`

Is it possible to add a "show in full screen button" in the controls view?
or alternatively - support a double tap on the player itself(like youtube/facebook for example)?
or both :-)

**Comment by halilozercan** [comment]
As you pointed out, exported features only allow you to add fullscreen option through controls. I also think that is not the best way to implement fullscreen transition. In the next release, I will look for possible ways like exporting a double click function through listeners.

**Comment by pravinyo** [comment]
you can get the similar effect by adding button in menu file and handling the event in onMenuItemSelected listner,

This is a sample code, in my code i stopped activity recreation and called following method,
setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);


I have placed the player in the coordinator layout and rest ui element in includedLayout so when fullscreen button is pressed i simple set the visibility of included layout to be gone and make the player to full screen

as shown below
@Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);

        if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
            findViewById(R.id.news_includedLayout).setVisibility(View.GONE);

            AppBarLayout appbar = findViewById(R.id.app_bar_layout);
            float heightDp = getResources().getDisplayMetrics().heightPixels;
            CoordinatorLayout.LayoutParams lp = (CoordinatorLayout.LayoutParams)appbar.getLayoutParams();
            lp.height = (int)heightDp;
            lp.width = getResources().getDisplayMetrics().widthPixels;

            findViewById(R.id.app_bar_layout).setLayoutParams(lp);

        } else if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT){
            findViewById(R.id.news_includedLayout).setVisibility(View.VISIBLE);
            AppBarLayout appbar = findViewById(R.id.app_bar_layout);

            CoordinatorLayout.LayoutParams lp = (CoordinatorLayout.LayoutParams)appbar.getLayoutParams();
            lp.height = 720;
            lp.width = getResources().getDisplayMetrics().widthPixels;

            findViewById(R.id.app_bar_layout).setLayoutParams(lp);
        }
    }
