### ISSUE TITLE
Plackback in background like music player

### ISSUE THREAD

**Issue by kksingla** [halilozercan/BetterVideoPlayer#49]
How to play video in the background like a music player play songs in the background and user can use the device. 

Tried this, but unable to integrate BetterVideoPlayer and i also found the illegalStateException:
https://stackoverflow.com/questions/8830111/integrating-video-file-in-android-app-as-app-background

03-05 15:27:31.103 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err: java.lang.IllegalStateException
03-05 15:27:31.103 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.media.MediaPlayer.prepareAsync(Native Method)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at com.example.kushaalsingla.contentsharingdemo.VideoPlayOnSurfaceView.surfaceCreated(VideoPlayOnSurfaceView.java:59)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.SurfaceView.updateWindow(SurfaceView.java:597)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:243)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.View.dispatchWindowVisibilityChanged(View.java:9663)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1310)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1310)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1310)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1310)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1310)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1310)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1415)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6064)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:672)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:608)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.os.Handler.handleCallback(Handler.java:742)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.os.Looper.loop(Looper.java:157)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5555)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
03-05 15:27:31.104 24084-24084/com.example.kushaalsingla.contentsharingdemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

**Comment by halilozercan** [comment]
I'm sorry but there are other great libraries and tools to achieve this. BetterVideoPlayer only focuses on Video experience.
