### ISSUE TITLE
what is SubtitleView?

### ISSUE THREAD

**Issue by tmxd09887** [halilozercan/BetterVideoPlayer#51]
-- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
-- [ ] I have verified that I am using the latest version of Better Video Player.
-- [ ] I have given my issue a non-generic title.
-- [ ] I have read over the documentation (before asking questions on how to do something).

Hi

I just downloaded demo,and add this:

// Online SUBRIP subtitle
bvp.setCaptions("https://www.example.com/subrip.srt", SubtitleView.SubtitleMime.SUBRIP);

but I dont know what is SubtitleView?

**Comment by halilozercan** [comment]
SubtitleView is a helper view for BetterVideoPlayer. When given a local or remote HTTP/S source, SubtitleView would sync with the player and show subtitles(captions).
