### ISSUE TITLE
Brightness gesture doesnt work on first try

### ISSUE THREAD

**Issue by UGhari** [halilozercan/BetterVideoPlayer#58]
- - Better Video Player version: `1.2.alpha1
- - Device OS version: `7.0`
- - Device Manufacturer: `Samsung`
- - Device Name: `Galaxy S7`

Brightness sider doesnt work on first try. Steps required to reproduce:

1) Start video with a source and let the video start playing
2) Swipe up to change the brightness

Expected outcome:
Brightness number should become positive and I should physically see the brightness of the screen go up.

Actual outcome:
Brightness is set to 0 and stays at zero even if I am swiping up or down. Once I release my finger from the screen and swipe up/down again on left side of the screen only then does the brightness change correctly.

Below is my implementation:

```
public class Player extends AppCompatActivity implements BetterVideoCallback {

    private BetterVideoPlayer player;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_player);

        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);

        player = findViewById(R.id.player);
        player.setCallback(this);
        player.setSource(Uri.parse(getIntent().getStringExtra("movieURL")));
        player.getToolbar().setTitle(getIntent().getStringExtra("movieTitle"));
        player.enableSwipeGestures(getWindow());
        player.setLoadingStyle(2);

    }
    }
    ...
}
```
and here is my XML:

```
<com.halilibo.bettervideoplayer.BetterVideoPlayer
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/player"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:bvp_gestureType="SwipeGesture"
        app:bvp_autoPlay="true" />
```

Ive also tried using swipe gestures only in XML, and then only in the code. Both times I get the same outcome

**Comment by VivekChodvadiya** [comment]
Any solution? I am also facing this...
