### ISSUE TITLE
Ability to autohide the controls after n seconds

### ISSUE THREAD

**Issue by autovalue** [halilozercan/BetterVideoPlayer#6]
Currently the controls stay up indefinitely until you tap again.

**Comment by halilozercan** [comment]
This was available in original EasyVideoPlayer. I don't remember why it was removed. It's an important feature and should be added back.

**Comment by autovalue** [comment]
Ohh cool, just used that option and it seems to hide it after pressing the play button.
However it doesn't autohide after seeking or tapping the screen while the video is still playing.

For better flexibility, it would make sense to change the attribute name to something like `autoHideDuration` and if it's more than 0, the autohide behaviour will be used (along with the specified duration).
