### ISSUE TITLE
Failed to resolve: com.github.halilozercan:BetterVideoPlayer:1.2.alpha1

### ISSUE THREAD

**Issue by NizNsm** [halilozercan/BetterVideoPlayer#64]
Iam facing this issue while syncing the gradle 

`Failed to resolve: com.github.halilozercan:BetterVideoPlayer:1.2.alpha1`

**Comment by NizNsm** [comment]
Goodness.! The issue was missing of : 	

```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```

**Comment by ZyronAlex** [comment]
Hi I'm having a similar problem, when I try to synchronize the project I get this error:

error: resource style/SpinKitView.Large.FadingCircle (aka com.tecapps.AnimeC:style/SpinKitView.Large.FadingCircle) not found.
Message{kind=ERROR, text=error: resource style/SpinKitView.Large.FadingCircle (aka com.tecapps.AnimeC:style/SpinKitView.Large.FadingCircle) not found., sources=[C:\Users\alexbelo\.gradle\caches\transforms-1\files-1.1\BetterVideoPlayer-1.2.alpha1.aar\e2f50c251a91c492666e421ad6fca080\res\layout\bvp_include_progress.xml:7], original message=, tool name=Optional.of(AAPT)}

**Comment by sriramr98** [comment]
@ZyronAlex Even I'm facing this issue. Any help would be appretiated.

**Comment by piotrkalitka** [comment]
Looks like there is missing dependency to [https://github.com/ybq/Android-SpinKit](this):
implementation 'com.github.ybq:Android-SpinKit:1.1.0'

**Comment by ZyronAlex** [comment]
@piotrkalitka  
this dependency, is from BetterPlayer ?
why do I have to add another library to use BetterPlayer, it should not be implemented internally

**Comment by piotrkalitka** [comment]
I am not the author of this lib, so I can't tell you why you need to implement this on manually, but this solves the problem until author will fix this in next release

**Comment by ZyronAlex** [comment]
Thk man, this really solves the problem

**Comment by sriramr98** [comment]
Actually, this dependency is present in the library if you explore the gradle files. I don't know why it isn't working.

**Comment by halilozercan** [comment]
Hey guys, I'm sorry for getting back this slow. 

Usually the problem is forgetting to add jitpack in repositories list.

> Goodness.! The issue was missing of :
```
allprojects {
        repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```
However, now I realize that SpinKit may also cause problems. The funny thing is that as you have already mentioned, SpinKit exists as a dependency in this library. Maybe new gradle version is causing problems, I'm not really sure.

As a result, I will probably remove this dependency and go back to default android progress style while having this progressbar customizable by the app.

**Comment by malavancs** [comment]
Still facing the problem
