### ISSUE TITLE
Help with the menu background color

### ISSUE THREAD

**Issue by TurtleForGaming** [halilozercan/BetterVideoPlayer#68]
-###### Include the following:
- - Better Video Player version: `1.2.alpha1`
- - Device OS version: `7.1`
- - Device Manufacturer: `Oneplus`
- - Device Name: `One`
-

How to change the background color of the menu. I iflate the menu like this :
```java
mBetterVideoPlayer.getToolbar().inflateMenu()
```
but depending on my theme it's written in white and i do not know how to change the background color of the menu

**Comment by halilozercan** [comment]
```bvp.getToolbar().setPopupTheme(resId);```

You can give theme id to toolbar like this.
