### ISSUE TITLE
HLS video skips when bitrate changes

### ISSUE THREAD

**Issue by LeoSnek** [halilozercan/BetterVideoPlayer#74]
[✓] I have verified there are no duplicate active or recent bugs, questions, or requests
[✓] I have verified that I am using the latest version of Better Video Player.
[✓] I have given my issue a non-generic title.
[✓] I have read over the documentation (before asking questions on how to do something).

- Better Video Player version: `1.2.alpha1`
- Device OS version: `8.0.0`
- Device Manufacturer: `Samsung`
- Device Name: `Galaxy S7 Edge`

I'm playing HLS files hosted on Vimeo. The video starts to play as normal at a low bit rate but when the bit rate changes to a higher quality, normally after 5 or so seconds, the video playback skips a few seconds forwards.

I also tried using this available stream: https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8 and when the bit rate changes the video pauses a second but doesn't seem to skip. However this is also less than ideal.

My videos are also being used on iOS and bit rate changes are handled seamlessly. 

What can I do to improve this?

**Comment by halilozercan** [comment]
Android Stock Media Player Codecs would be insufficient for this kind of
use case. I'd suggest you to use a media player based on ExoPlayer. It is
definitely more capable and also engineered by Google.

**Comment by LeoSnek** [comment]
Okay fair point. I have been trying that actually and have managed to get things working using https://github.com/brianwernick/ExoMedia.

Thanks for getting back to me so quickly.
