### ISSUE TITLE
VTT parser isn't working properly.

### ISSUE THREAD

**Issue by autovalue** [halilozercan/BetterVideoPlayer#9]
It doesn't work with any of the following vtt subtitle files:

https://iandevlin.github.io/mdn/video-player-with-captions/subtitles/vtt/sintel-en.vtt
https://iandevlin.github.io/mdn/video-player-with-captions/subtitles/vtt/sintel-de.vtt
https://iandevlin.github.io/mdn/video-player-with-captions/subtitles/vtt/sintel-es.vtt

source: https://iandevlin.github.io/mdn/video-player-with-captions/

**Comment by autovalue** [comment]
I'm adding custom styles to the videoplayer subtitles via `findViewById`, but on the event that the parser fails to retrieve a valid subtitle, there should be a listener that notifies users accordingly.

**Comment by halilozercan** [comment]
Supported subtitle format is WEBVTT, not VTT. [https://w3c.github.io/webvtt/](In here), you can see that WEBVTT format does not have index lines at each entry.

**Comment by halilozercan** [comment]
> I'm adding custom styles to the videoplayer subtitles via findViewById, but on the event that the parser fails to retrieve a valid subtitle, there should be a listener that notifies users accordingly.

I understand you are going for a hacky solution because library currently does not support styling subtitles. Support for styling will be added in near feature :)

**Comment by halilozercan** [comment]
- [ ] VTT parsing option

Remaining styling problem is being discussed under #3

**Comment by autovalue** [comment]
> Supported subtitle format is WEBVTT, not VTT. In here , you can see that WEBVTT format does not have index lines at each entry.

My bad, wasn't aware that there was a distinction. I don't think support for it is that urgent in that case - but like I previously, it would be nice if the library was architectured in a way to allow people to pass in custom components.

> Support for styling will be added in near feature :)

Glad to hear that.
