### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by thatsenam** [halilozercan/BetterVideoPlayer#91]
Error Log

AGPBI: {"kind":"error","text":"error: resource style/SpinKitView.Large.FadingCircle (aka movietube.movietube:style/SpinKitView.Large.FadingCircle) not found.","sources":[{"file":"C:\\Users\\Enam\\.gradle\\caches\\transforms-1\\files-1.1\\BetterVideoPlayer-1.2.alpha1.aar\\cae2c8bec414f06229759b4c01e117fe\\res\\layout\\bvp_include_progress.xml","position":{"startLine":6}}],"original":"","tool":"AAPT"}

I just used 
implementation 'com.github.halilozercan:BetterVideoPlayer:1.2.alpha1'

**Comment by halilozercan** [comment]
as told in updated readme, I'd suggest you to use

```
compile 'com.github.halilozercan:BetterVideoPlayer:kotlin-SNAPSHOT'
```
